apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: lab2
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app: frontend
