apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: lab2
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootpassword"
  MYSQL_PASSWORD: "lab2pass"
  DB_USER: "lab2user"
  DB_PASSWORD: "lab2pass"
